import path from "node:path";

const CLIENT_DIRECTORY = "dist/client";
const GENERATED_DIRECTORY = ".deploy";
const GENERATED_MANIFEST = path.join(
	GENERATED_DIRECTORY,
	"embedded-client-assets.ts",
);

function toPosixPath(filepath: string): string {
	return filepath.split(path.sep).join(path.posix.sep);
}

function toImportSpecifier(filepath: string): string {
	const relativePath = toPosixPath(
		path.relative(GENERATED_DIRECTORY, filepath),
	);

	return relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
}

const glob = new Bun.Glob("**/*");
const assetPaths: string[] = [];

for await (const relativePath of glob.scan({ cwd: CLIENT_DIRECTORY })) {
	const filepath = path.join(CLIENT_DIRECTORY, relativePath);
	const file = Bun.file(filepath);

	if (!(await file.exists()) || file.size === 0) {
		continue;
	}

	assetPaths.push(filepath);
}

if (assetPaths.length === 0) {
	throw new Error(`No client assets found in ${CLIENT_DIRECTORY}.`);
}

assetPaths.sort((left, right) => left.localeCompare(right));
await Bun.$`mkdir -p ${GENERATED_DIRECTORY}`;
await Bun.write(
	GENERATED_MANIFEST,
	[
		"// Generated by scripts/generate-embedded-client-manifest.ts.",
		...assetPaths.map(
			(filepath) =>
				`import ${JSON.stringify(toImportSpecifier(filepath))} with { type: "file" };`,
		),
		"",
	].join("\n"),
);

console.log(
	`Generated ${GENERATED_MANIFEST} with ${assetPaths.length.toString()} embedded client assets.`,
);
