/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApiBotRouteImport } from './routes/api/bot'
import { Route as AppGroupsGroupIdRouteRouteImport } from './routes/app/groups/$groupId/route'
import { Route as AppGroupsGroupIdIndexRouteImport } from './routes/app/groups/$groupId/index'
import { Route as AppGroupsGroupIdSettingsRouteImport } from './routes/app/groups/$groupId/settings'
import { Route as AppGroupsGroupIdAddExpenseRouteImport } from './routes/app/groups/$groupId/add-expense'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiBotRoute = ApiBotRouteImport.update({
  id: '/api/bot',
  path: '/api/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGroupsGroupIdRouteRoute = AppGroupsGroupIdRouteRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupsGroupIdIndexRoute = AppGroupsGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGroupsGroupIdRouteRoute,
} as any)
const AppGroupsGroupIdSettingsRoute =
  AppGroupsGroupIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppGroupsGroupIdRouteRoute,
  } as any)
const AppGroupsGroupIdAddExpenseRoute =
  AppGroupsGroupIdAddExpenseRouteImport.update({
    id: '/add-expense',
    path: '/add-expense',
    getParentRoute: () => AppGroupsGroupIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/api/bot': typeof ApiBotRoute
  '/app/': typeof AppIndexRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdRouteRouteWithChildren
  '/app/groups/$groupId/add-expense': typeof AppGroupsGroupIdAddExpenseRoute
  '/app/groups/$groupId/settings': typeof AppGroupsGroupIdSettingsRoute
  '/app/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bot': typeof ApiBotRoute
  '/app': typeof AppIndexRoute
  '/app/groups/$groupId/add-expense': typeof AppGroupsGroupIdAddExpenseRoute
  '/app/groups/$groupId/settings': typeof AppGroupsGroupIdSettingsRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/api/bot': typeof ApiBotRoute
  '/app/': typeof AppIndexRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdRouteRouteWithChildren
  '/app/groups/$groupId/add-expense': typeof AppGroupsGroupIdAddExpenseRoute
  '/app/groups/$groupId/settings': typeof AppGroupsGroupIdSettingsRoute
  '/app/groups/$groupId/': typeof AppGroupsGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/bot'
    | '/app/'
    | '/app/groups/$groupId'
    | '/app/groups/$groupId/add-expense'
    | '/app/groups/$groupId/settings'
    | '/app/groups/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/bot'
    | '/app'
    | '/app/groups/$groupId/add-expense'
    | '/app/groups/$groupId/settings'
    | '/app/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/bot'
    | '/app/'
    | '/app/groups/$groupId'
    | '/app/groups/$groupId/add-expense'
    | '/app/groups/$groupId/settings'
    | '/app/groups/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiBotRoute: typeof ApiBotRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/bot': {
      id: '/api/bot'
      path: '/api/bot'
      fullPath: '/api/bot'
      preLoaderRoute: typeof ApiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/groups/$groupId': {
      id: '/app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/app/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/groups/$groupId/': {
      id: '/app/groups/$groupId/'
      path: '/'
      fullPath: '/app/groups/$groupId/'
      preLoaderRoute: typeof AppGroupsGroupIdIndexRouteImport
      parentRoute: typeof AppGroupsGroupIdRouteRoute
    }
    '/app/groups/$groupId/settings': {
      id: '/app/groups/$groupId/settings'
      path: '/settings'
      fullPath: '/app/groups/$groupId/settings'
      preLoaderRoute: typeof AppGroupsGroupIdSettingsRouteImport
      parentRoute: typeof AppGroupsGroupIdRouteRoute
    }
    '/app/groups/$groupId/add-expense': {
      id: '/app/groups/$groupId/add-expense'
      path: '/add-expense'
      fullPath: '/app/groups/$groupId/add-expense'
      preLoaderRoute: typeof AppGroupsGroupIdAddExpenseRouteImport
      parentRoute: typeof AppGroupsGroupIdRouteRoute
    }
  }
}

interface AppGroupsGroupIdRouteRouteChildren {
  AppGroupsGroupIdAddExpenseRoute: typeof AppGroupsGroupIdAddExpenseRoute
  AppGroupsGroupIdSettingsRoute: typeof AppGroupsGroupIdSettingsRoute
  AppGroupsGroupIdIndexRoute: typeof AppGroupsGroupIdIndexRoute
}

const AppGroupsGroupIdRouteRouteChildren: AppGroupsGroupIdRouteRouteChildren = {
  AppGroupsGroupIdAddExpenseRoute: AppGroupsGroupIdAddExpenseRoute,
  AppGroupsGroupIdSettingsRoute: AppGroupsGroupIdSettingsRoute,
  AppGroupsGroupIdIndexRoute: AppGroupsGroupIdIndexRoute,
}

const AppGroupsGroupIdRouteRouteWithChildren =
  AppGroupsGroupIdRouteRoute._addFileChildren(
    AppGroupsGroupIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppGroupsGroupIdRouteRoute: typeof AppGroupsGroupIdRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppGroupsGroupIdRouteRoute: AppGroupsGroupIdRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiBotRoute: ApiBotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
