/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBotRouteImport } from './routes/api/bot'
import { Route as AppIdRouteRouteImport } from './routes/app/$id/route'
import { Route as AppIdGroupGroupIdRouteRouteImport } from './routes/app/$id/group/$groupId/route'
import { Route as AppIdGroupGroupIdIndexRouteImport } from './routes/app/$id/group/$groupId/index'
import { Route as AppIdGroupGroupIdSettingsRouteImport } from './routes/app/$id/group/$groupId/settings'
import { Route as AppIdGroupGroupIdAddExpenseRouteImport } from './routes/app/$id/group/$groupId/add-expense'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotRoute = ApiBotRouteImport.update({
  id: '/api/bot',
  path: '/api/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdRouteRoute = AppIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIdGroupGroupIdRouteRoute = AppIdGroupGroupIdRouteRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdGroupGroupIdIndexRoute = AppIdGroupGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdGroupGroupIdRouteRoute,
} as any)
const AppIdGroupGroupIdSettingsRoute =
  AppIdGroupGroupIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppIdGroupGroupIdRouteRoute,
  } as any)
const AppIdGroupGroupIdAddExpenseRoute =
  AppIdGroupGroupIdAddExpenseRouteImport.update({
    id: '/add-expense',
    path: '/add-expense',
    getParentRoute: () => AppIdGroupGroupIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$id': typeof AppIdRouteRouteWithChildren
  '/api/bot': typeof ApiBotRoute
  '/app/$id/group/$groupId': typeof AppIdGroupGroupIdRouteRouteWithChildren
  '/app/$id/group/$groupId/add-expense': typeof AppIdGroupGroupIdAddExpenseRoute
  '/app/$id/group/$groupId/settings': typeof AppIdGroupGroupIdSettingsRoute
  '/app/$id/group/$groupId/': typeof AppIdGroupGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$id': typeof AppIdRouteRouteWithChildren
  '/api/bot': typeof ApiBotRoute
  '/app/$id/group/$groupId/add-expense': typeof AppIdGroupGroupIdAddExpenseRoute
  '/app/$id/group/$groupId/settings': typeof AppIdGroupGroupIdSettingsRoute
  '/app/$id/group/$groupId': typeof AppIdGroupGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$id': typeof AppIdRouteRouteWithChildren
  '/api/bot': typeof ApiBotRoute
  '/app/$id/group/$groupId': typeof AppIdGroupGroupIdRouteRouteWithChildren
  '/app/$id/group/$groupId/add-expense': typeof AppIdGroupGroupIdAddExpenseRoute
  '/app/$id/group/$groupId/settings': typeof AppIdGroupGroupIdSettingsRoute
  '/app/$id/group/$groupId/': typeof AppIdGroupGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$id'
    | '/api/bot'
    | '/app/$id/group/$groupId'
    | '/app/$id/group/$groupId/add-expense'
    | '/app/$id/group/$groupId/settings'
    | '/app/$id/group/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/$id'
    | '/api/bot'
    | '/app/$id/group/$groupId/add-expense'
    | '/app/$id/group/$groupId/settings'
    | '/app/$id/group/$groupId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$id'
    | '/api/bot'
    | '/app/$id/group/$groupId'
    | '/app/$id/group/$groupId/add-expense'
    | '/app/$id/group/$groupId/settings'
    | '/app/$id/group/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiBotRoute: typeof ApiBotRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot': {
      id: '/api/bot'
      path: '/api/bot'
      fullPath: '/api/bot'
      preLoaderRoute: typeof ApiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$id': {
      id: '/app/$id'
      path: '/$id'
      fullPath: '/app/$id'
      preLoaderRoute: typeof AppIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$id/group/$groupId': {
      id: '/app/$id/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/app/$id/group/$groupId'
      preLoaderRoute: typeof AppIdGroupGroupIdRouteRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/$id/group/$groupId/': {
      id: '/app/$id/group/$groupId/'
      path: '/'
      fullPath: '/app/$id/group/$groupId/'
      preLoaderRoute: typeof AppIdGroupGroupIdIndexRouteImport
      parentRoute: typeof AppIdGroupGroupIdRouteRoute
    }
    '/app/$id/group/$groupId/settings': {
      id: '/app/$id/group/$groupId/settings'
      path: '/settings'
      fullPath: '/app/$id/group/$groupId/settings'
      preLoaderRoute: typeof AppIdGroupGroupIdSettingsRouteImport
      parentRoute: typeof AppIdGroupGroupIdRouteRoute
    }
    '/app/$id/group/$groupId/add-expense': {
      id: '/app/$id/group/$groupId/add-expense'
      path: '/add-expense'
      fullPath: '/app/$id/group/$groupId/add-expense'
      preLoaderRoute: typeof AppIdGroupGroupIdAddExpenseRouteImport
      parentRoute: typeof AppIdGroupGroupIdRouteRoute
    }
  }
}

interface AppIdGroupGroupIdRouteRouteChildren {
  AppIdGroupGroupIdAddExpenseRoute: typeof AppIdGroupGroupIdAddExpenseRoute
  AppIdGroupGroupIdSettingsRoute: typeof AppIdGroupGroupIdSettingsRoute
  AppIdGroupGroupIdIndexRoute: typeof AppIdGroupGroupIdIndexRoute
}

const AppIdGroupGroupIdRouteRouteChildren: AppIdGroupGroupIdRouteRouteChildren =
  {
    AppIdGroupGroupIdAddExpenseRoute: AppIdGroupGroupIdAddExpenseRoute,
    AppIdGroupGroupIdSettingsRoute: AppIdGroupGroupIdSettingsRoute,
    AppIdGroupGroupIdIndexRoute: AppIdGroupGroupIdIndexRoute,
  }

const AppIdGroupGroupIdRouteRouteWithChildren =
  AppIdGroupGroupIdRouteRoute._addFileChildren(
    AppIdGroupGroupIdRouteRouteChildren,
  )

interface AppIdRouteRouteChildren {
  AppIdGroupGroupIdRouteRoute: typeof AppIdGroupGroupIdRouteRouteWithChildren
}

const AppIdRouteRouteChildren: AppIdRouteRouteChildren = {
  AppIdGroupGroupIdRouteRoute: AppIdGroupGroupIdRouteRouteWithChildren,
}

const AppIdRouteRouteWithChildren = AppIdRouteRoute._addFileChildren(
  AppIdRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIdRouteRoute: typeof AppIdRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIdRouteRoute: AppIdRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiBotRoute: ApiBotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
