/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIdRouteImport } from './routes/app.$id'
import { Route as ApiBotRouteImport } from './routes/api/bot'
import { Route as AppIdGroupGroupIdRouteImport } from './routes/app.$id.group.$groupId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdRoute = AppIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiBotRoute = ApiBotRouteImport.update({
  id: '/api/bot',
  path: '/api/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdGroupGroupIdRoute = AppIdGroupGroupIdRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => AppIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/bot': typeof ApiBotRoute
  '/app/$id': typeof AppIdRouteWithChildren
  '/app/$id/group/$groupId': typeof AppIdGroupGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/bot': typeof ApiBotRoute
  '/app/$id': typeof AppIdRouteWithChildren
  '/app/$id/group/$groupId': typeof AppIdGroupGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/bot': typeof ApiBotRoute
  '/app/$id': typeof AppIdRouteWithChildren
  '/app/$id/group/$groupId': typeof AppIdGroupGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/api/bot' | '/app/$id' | '/app/$id/group/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/api/bot' | '/app/$id' | '/app/$id/group/$groupId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/bot'
    | '/app/$id'
    | '/app/$id/group/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiBotRoute: typeof ApiBotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$id': {
      id: '/app/$id'
      path: '/$id'
      fullPath: '/app/$id'
      preLoaderRoute: typeof AppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/bot': {
      id: '/api/bot'
      path: '/api/bot'
      fullPath: '/api/bot'
      preLoaderRoute: typeof ApiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$id/group/$groupId': {
      id: '/app/$id/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/app/$id/group/$groupId'
      preLoaderRoute: typeof AppIdGroupGroupIdRouteImport
      parentRoute: typeof AppIdRoute
    }
  }
}

interface AppIdRouteChildren {
  AppIdGroupGroupIdRoute: typeof AppIdGroupGroupIdRoute
}

const AppIdRouteChildren: AppIdRouteChildren = {
  AppIdGroupGroupIdRoute: AppIdGroupGroupIdRoute,
}

const AppIdRouteWithChildren = AppIdRoute._addFileChildren(AppIdRouteChildren)

interface AppRouteChildren {
  AppIdRoute: typeof AppIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIdRoute: AppIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiBotRoute: ApiBotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
